### ISSUE TITLE
External resources

### ISSUE THREAD

**Issue by cjessett** [wrenngreg/TeaCozy#3]
(Subtlety) [Instead of linking to external resources](https://github.com/wrenngreg/TeaCozy/blob/70394b65bfb77ca21f25b18f25850cafcbac6dc5/index.html#L13) download the images, include them in the project, and reference them locally. Since url's can break or change, including the content locally prevents unexpected changes.

**Comment by wrenngreg** [comment]
@cjessett Makes perfect sense. Will do that going forward! Thanks
